const items=[
 {id:1,type:'found',title:'黑色无线耳机',place:'图书馆三楼',time:'10 分钟前',date:'2026-09-28',symbol:'◉',color:'#dfe8ef',description:'在靠窗自习区座位下发现，黑色充电盒，盒盖有一处浅色划痕。'},
 {id:2,type:'lost',title:'蓝色校园卡套',place:'一食堂附近',time:'35 分钟前',date:'2026-09-28',symbol:'▣',color:'#dcece6',description:'透明蓝色卡套，挂着一条深蓝色短挂绳，内有校园卡。'},
 {id:3,type:'found',title:'米白色折叠伞',place:'西三教学楼',time:'1 小时前',date:'2026-09-28',symbol:'⌁',color:'#f6e6cf',description:'在一楼大厅长椅旁发现，米白色六骨折叠伞，手柄有木纹。'},
 {id:4,type:'lost',title:'高等数学教材',place:'田径场看台',time:'2 小时前',date:'2026-09-28',symbol:'▤',color:'#f0ded8',description:'同济版高等数学上册，封面右上角写有班级和姓氏。'}
];
const state={filter:'all',selected:items[0],mine:[items[1]]};
const pages=[...document.querySelectorAll('.page')];
const nav=[...document.querySelectorAll('.bottom-nav button[data-page]')];
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusLabel=i=>i.resolved?(i.type==='lost'?'已找到':'已归还'):(i.type==='lost'?'寻找中':'待认领');
const itemCard=i=>`<button class="item" data-id="${i.id}"><span class="item-visual" style="background:${i.color}">${i.symbol}</span><span><span class="item-top"><span class="tag ${i.type}">${i.type==='lost'?'寻物':'招领'}</span><time>${i.time}</time></span><h3>${escapeHTML(i.title)}</h3><p>${escapeHTML(i.place)} · ${statusLabel(i)}</p></span></button>`;
function refreshFeeds(){renderFeed(state.filter==='all'?items:items.filter(i=>i.type===state.filter));renderFeed(state.mine,'mine-feed');search(document.getElementById('search-input').value);}
function renderFeed(list=items,target='feed'){document.getElementById(target).innerHTML=list.length?list.map(itemCard).join(''):'<p class="empty">没有找到相关信息，换个关键词试试。</p>';}
function showPage(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));nav.forEach(b=>b.classList.toggle('active',b.dataset.page===id));document.querySelector('.bottom-nav').hidden=id==='success';window.scrollTo(0,0);}
function showDetail(id){const i=items.find(x=>x.id===Number(id))||state.mine.find(x=>x.id===Number(id));if(!i)return;state.selected=i;document.getElementById('detail-cover').style.background=i.color;document.getElementById('detail-symbol').textContent=i.symbol;const tag=document.getElementById('detail-type');tag.textContent=i.type==='lost'?'寻物信息':'招领信息';tag.className=`status-tag tag ${i.type}`;document.getElementById('detail-time').textContent=i.time;document.getElementById('detail-title').textContent=i.title;document.getElementById('detail-description').textContent=i.description;document.getElementById('detail-place').textContent=i.place;document.getElementById('detail-date').textContent=i.date;document.getElementById('detail-status').textContent=statusLabel(i);const manage=document.getElementById('resolve-btn');manage.hidden=!state.mine.includes(i);manage.textContent=i.resolved?'恢复为未完成':(i.type==='lost'?'标记已找到':'标记已归还');showPage('detail');}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page)showPage(page.dataset.page);const publish=e.target.closest('[data-publish-type]');if(publish){showPage('publish');document.querySelector(`[name=type][value=${publish.dataset.publishType}]`).checked=true}const card=e.target.closest('.item');if(card)showDetail(card.dataset.id);const chip=e.target.closest('.chips button');if(chip){document.getElementById('search-input').value=chip.textContent;search(chip.textContent)}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));state.filter=b.dataset.filter;renderFeed(state.filter==='all'?items:items.filter(i=>i.type===state.filter))}));
function search(value){const q=value.trim().toLowerCase();const found=items.filter(i=>`${i.title}${i.place}${i.description}`.toLowerCase().includes(q));document.getElementById('search-meta').textContent=q?`找到 ${found.length} 条相关信息`:'推荐信息';renderFeed(q?found:items,'search-results')}
document.getElementById('search-input').addEventListener('input',e=>search(e.target.value));document.getElementById('clear-search').addEventListener('click',()=>{document.getElementById('search-input').value='';search('')});
function setDefaultDate(){const now=new Date();document.querySelector('[name=date]').value=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);}
document.getElementById('publish-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);for(const name of ['title','description','contact']){if(!String(data.get(name)).trim()){toast('请填写物品名称、特征和联系方式，不能只输入空格。');return;}}const newItem={id:Date.now(),type:data.get('type'),title:data.get('title').trim(),place:data.get('place'),time:'刚刚',date:data.get('date'),symbol:'◇',color:'#e7e4d8',description:data.get('description').trim(),contact:data.get('contact').trim(),resolved:false};items.unshift(newItem);state.mine.unshift(newItem);refreshFeeds();e.currentTarget.reset();setDefaultDate();showPage('success')});
document.getElementById('contact-btn').addEventListener('click',()=>toast(state.selected.contact?`联系方式：${state.selected.contact}`:'示例信息未提供真实联系方式。'));
document.getElementById('resolve-btn').addEventListener('click',()=>{if(!state.mine.includes(state.selected))return;state.selected.resolved=!state.selected.resolved;refreshFeeds();showDetail(state.selected.id);toast('状态已更新（本次会话内）');});
setDefaultDate();refreshFeeds();
const params=new URLSearchParams(location.search);if(params.has('capture'))document.documentElement.classList.add('capture');const preview=params.get('page');if(preview==='detail')showDetail(1);else if(preview&&document.getElementById(preview))showPage(preview);
