const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const {spawn}=require('node:child_process');
(async()=>{
 const started=new Date(),root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'lostfound-test-'));
 const url='http://127.0.0.1:18765', database=path.join(tmp,'test.db');
 let child,browser;
 async function start(){child=spawn('python',[path.join(root,'server.py'),'--port','18765','--database',database],{stdio:['ignore','pipe','pipe']});for(let n=0;n<50;n++){try{if((await fetch(url+'/api/items')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('测试服务未启动');}
 async function stop(){if(child&&!child.killed){child.kill();await new Promise(r=>child.once('exit',r));}}
 const results=[], check=async(id,name,fn)=>{await fn();results.push({id,name,result:'通过'});console.log(id+' PASS '+name);};
 try{
 await start();browser=await chromium.launch({channel:'msedge',headless:true});
 const ctx=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']});
 const page=await ctx.newPage(),other=await browser.newContext({viewport:{width:390,height:844}}),b=await other.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.waitForFunction(()=>document.getElementById('mode-note').textContent.includes('SQLite'));
 const go=async name=>page.locator('.bottom-nav [data-page="'+name+'"]').click();
 const fill=async(title,type='lost')=>{await go('publish');await page.locator('[name=type][value='+type+']').check();await page.locator('[name=title]').fill(title);await page.locator('[name=place]').fill('图书馆三楼');await page.locator('[name=category]').selectOption('电子设备');await page.locator('[name=description]').fill('蓝色外壳，测试数据');await page.locator('[name=contact]').fill('demo_contact_only');};
 const submit=async()=>{await page.locator('#submit-btn').click();await page.locator('#success').waitFor({state:'visible'});};
 const shot=async name=>{await page.locator('#toast').evaluate(el=>el.classList.remove('show'));await page.screenshot({path:path.join(root,'images',name+'.png'),fullPage:true});};
 const fixture=path.join(tmp,'photo.png'),fixturePage=await ctx.newPage();await fixturePage.setViewportSize({width:360,height:240});await fixturePage.setContent('<body style="margin:0;background:#e9eff5;display:grid;place-items:center;height:100vh"><svg width="200" height="180" viewBox="0 0 200 180"><path d="M40 95V75a60 60 0 0 1 120 0v20" fill="none" stroke="#34506c" stroke-width="16"/><rect x="25" y="85" width="35" height="65" rx="15" fill="#496d91"/><rect x="140" y="85" width="35" height="65" rx="15" fill="#496d91"/><text x="100" y="175" text-anchor="middle" font-size="12" fill="#34506c">TEST IMAGE</text></svg>');await fixturePage.screenshot({path:fixture});await fixturePage.close();
 await check('T01','空表单与全空格校验',async()=>{await go('publish');await page.locator('#submit-btn').click();assert.equal(await page.locator('[name=title]').evaluate(el=>el.validity.valueMissing),true);await fill('   ');await page.locator('#submit-btn').click();assert.match(await page.locator('#toast').textContent(),/空格/);});
 await check('T02','图片上传删除与发布',async()=>{await fill('蓝色测试耳机');await page.locator('#photo-input').setInputFiles([fixture,fixture]);await page.waitForFunction(()=>document.querySelectorAll('#photo-preview img').length===2);await page.locator('[data-remove-photo="1"]').click();assert.equal(await page.locator('#photo-preview img').count(),1);await shot('publish');await submit();await shot('success');await page.locator('#success-detail').click();assert.equal(await page.locator('#detail-gallery img').count(),1);await shot('detail');});
 await check('T03','刷新保留数据',async()=>{await page.reload();await page.locator('#feed .item').waitFor();assert.equal(await page.locator('#feed .item').count(),1);await shot('home');});
 await check('T04','另一个浏览器共享与权限拒绝',async()=>{await b.goto(url);await b.locator('#feed .item').waitFor();assert.equal(await b.locator('#feed .item').count(),1);await b.locator('#feed .item').click();assert.equal(await b.locator('#manage-actions').isVisible(),false);const token=await b.evaluate(()=>localStorage.getItem('lf-owner-v1'));const response=await fetch(url+'/api/items/1',{method:'PUT',headers:{'Content-Type':'application/json','X-Owner-Token':token},body:JSON.stringify({title:'越权改名'})});assert.equal(response.status,403);});
 await check('T05','组合筛选和日期边界',async()=>{await go('search');await page.locator('#search-input').fill('耳机');await page.locator('#filter-type').selectOption('lost');await page.locator('#filter-category').selectOption('电子设备');await page.locator('#filter-place').fill('图书馆');const date=await page.locator('#feed time').first().textContent();await page.locator('#filter-from').fill(date);await page.locator('#filter-to').fill(date);assert.equal(await page.locator('#search-results .item').count(),1);await shot('search');await page.locator('#filter-type').selectOption('found');assert.equal(await page.locator('#search-results .item').count(),0);await page.locator('#filter-from').fill('2026-10-10');await page.locator('#filter-to').fill('2026-10-01');assert.match(await page.locator('#search-error').textContent(),/不能晚于/);await page.locator('#reset-filters').click();});
 await check('T06','复制联系方式与图片放大',async()=>{await page.locator('#search-results .item').click();await page.locator('#contact-btn').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'demo_contact_only');await page.locator('[data-photo="0"]').click();assert.equal(await page.locator('#photo-dialog').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#photo-dialog').isVisible(),false);});
 await check('T07','编辑回填与保存',async()=>{await page.locator('#edit-btn').click();assert.equal(await page.locator('[name=title]').inputValue(),'蓝色测试耳机');assert.equal(await page.locator('#photo-preview img').count(),1);await page.locator('[name=title]').fill('蓝色耳机（已编辑）');await submit();await page.locator('#success-detail').click();assert.equal(await page.locator('#detail-title').textContent(),'蓝色耳机（已编辑）');});
 await check('T08','完成后公共列表移除且本人保留',async()=>{await page.locator('#resolve-btn').click();await page.waitForFunction(()=>document.getElementById('detail-status').textContent==='已找到');await go('home');assert.equal(await page.locator('#feed .item').count(),0);await go('mine');assert.equal(await page.locator('#mine-feed .item').count(),1);await shot('mine');await page.locator('#mine-feed .item').click();await page.locator('#resolve-btn').click();await page.waitForFunction(()=>document.getElementById('detail-status').textContent==='寻找中');});
 await check('T09','关闭与完成独立',async()=>{await page.locator('#close-btn').click();await page.waitForFunction(()=>document.getElementById('detail-status').textContent==='已关闭');await page.locator('#resolve-btn').click();await page.waitForFunction(()=>document.getElementById('resolve-btn').textContent==='恢复未完成');await page.locator('#close-btn').click();await page.waitForFunction(()=>document.getElementById('detail-status').textContent==='已找到');});
 await check('T10','服务重启保留数据库',async()=>{await stop();await start();await page.reload();await go('mine');await page.locator('#mine-feed .item').waitFor();assert.equal(await page.locator('#mine-feed .item').count(),1);});
 await check('T11','HTML输入按文本显示与招领文案',async()=>{await fill('<img src=x onerror=alert(1)>','found');await submit();await page.locator('#success-detail').click();assert.equal(await page.locator('#detail-title').textContent(),'<img src=x onerror=alert(1)>');await page.locator('#resolve-btn').click();await page.waitForFunction(()=>document.getElementById('detail-status').textContent==='已归还');});
 await check('T12','移动端和桌面布局',async()=>{for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const name of ['home','search','publish','mine']){await go(name);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,width+' '+name);}}await shot('desktop');await page.setViewportSize({width:320,height:844});await go('publish');await shot('mobile-320');});
 await check('T13','删除取消与确认',async()=>{await go('mine');await page.locator('#mine-feed .item').first().click();page.once('dialog',d=>d.dismiss());await page.locator('#delete-btn').click();assert.equal(await page.locator('#detail').isVisible(),true);page.once('dialog',d=>d.accept());await page.locator('#delete-btn').click();await page.locator('#mine').waitFor({state:'visible'});assert.equal(await page.locator('#mine-feed .item').count(),1);});
 await check('T14','保存失败保留表单及无脚本错误',async()=>{await fill('失败保留');await page.route('**/api/items',route=>route.abort());await page.locator('#submit-btn').click();await page.waitForFunction(()=>!document.getElementById('submit-btn').disabled);assert.equal(await page.locator('[name=title]').inputValue(),'失败保留');assert.equal(await page.locator('#publish').isVisible(),true);assert.deepEqual(errors,[]);});
 await check('T15','静态体验版刷新保留本地数据',async()=>{const demoContext=await browser.newContext(),d=await demoContext.newPage();await d.goto(require('node:url').pathToFileURL(path.join(root,'index.html')).href);await d.locator('#feed .item').first().waitFor();await d.locator('.bottom-nav [data-page=publish]').click();for(const [key,value]of Object.entries({title:'本地体验测试',place:'图书馆',description:'虚构物品',contact:'demo_only'}))await d.locator('[name='+key+']').fill(value);await d.locator('#submit-btn').click();await d.locator('#success').waitFor({state:'visible'});await d.reload();assert.equal(await d.locator('#feed .item').count(),5);await demoContext.close();});
 fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({startedAt:started.toISOString(),finishedAt:new Date().toISOString(),engine:'Microsoft Edge headless + Python SQLite server',results},null,2));
 }finally{if(browser)await browser.close();await stop();}
})().catch(e=>{console.error(e);process.exitCode=1;});
